#!/usr/bin/env python3
"""Android-friendly Kivy GUI for movie search on lordfilm/kinogo/filmix.

Build instructions (Linux/macOS):
    1. Install buildozer (pip install buildozer) and android SDK/NDK deps.
    2. Edit buildozer.spec (generated by `buildozer init`) to include
       requirements: python3,kivy,requests,beautifulsoup4,lxml,cloudscraper
       source.include_exts = py,kv
    3. Copy this file and site_parsers.py into the same directory.
    4. Run: buildozer -v android debug
       The resulting APK will be at bin/*.apk.

The UI is intentionally simple: a text field for query, a dropdown for site,
"Search" button, and a scrollable list of results (title + link).
"""
from __future__ import annotations

import threading
from typing import List

from kivy.app import App
from kivy.lang import Builder
from kivy.properties import StringProperty, ListProperty
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.recycleview import RecycleView
from kivy.uix.label import Label
from kivy.uix.popup import Popup

from site_parsers import SITE_PARSERS, Movie

KV = """
<Root>:
    orientation: 'vertical'
    padding: 10
    spacing: 10

    BoxLayout:
        size_hint_y: None
        height: '40dp'
        spacing: 10

        Spinner:
            id: site_spinner
            text: root.selected_site
            values: root.sites
            on_text: root.selected_site = self.text

        TextInput:
            id: query_input
            hint_text: 'Введите название фильма'
            multiline: False

        Button:
            text: 'Поиск'
            size_hint_x: None
            width: '80dp'
            on_release: root.on_search(query_input.text)

    RecycleView:
        id: rv
        viewclass: 'Label'
        RecycleBoxLayout:
            default_size: None, dp(40)
            default_size_hint: 1, None
            size_hint_y: None
            height: self.minimum_height
            orientation: 'vertical'
"""


class Root(BoxLayout):
    sites = ListProperty(list(SITE_PARSERS.keys()))
    selected_site = StringProperty(list(SITE_PARSERS.keys())[0])

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def on_search(self, query: str) -> None:
        query = query.strip()
        if not query:
            self._show_error("Введите запрос")
            return

        def worker():
            try:
                ParserCls = SITE_PARSERS[self.selected_site]
                parser = ParserCls(timeout=25)
                results = parser.search(query)
                self._update_results(results)
            except Exception as exc:
                self._show_error(str(exc))

        threading.Thread(target=worker, daemon=True).start()

    def _update_results(self, movies: List[Movie]):
        # UI updates must be scheduled on main thread
        from kivy.clock import Clock

        def _populate(_):
            rv = self.ids.rv
            if not movies:
                rv.data = [{"text": "Ничего не найдено", "markup": False}]
                return
            rv.data = [
                {"text": f"[b]{m.title}[/b]\n[url]{m.url}[/url]", "markup": True}
                for m in movies
            ]

        Clock.schedule_once(_populate)

    def _show_error(self, message: str):
        from kivy.clock import Clock

        def _pop(_):
            popup = Popup(title="Ошибка",
                          content=Label(text=message),
                          size_hint=(0.8, 0.3))
            popup.open()

        Clock.schedule_once(_pop)


class MovieSearchApp(App):
    def build(self):
        Builder.load_string(KV)
        return Root()


if __name__ == '__main__':
    MovieSearchApp().run()